GET http://localhost:5245/doctor/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIyYmIyN2Q5MiIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjEiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzMzUsImV4cCI6MTc2MTE1MzEzNSwiaWF0IjoxNzUzMjA0MzM2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.vClLBEnYOL90mOoM-jD21D6EYE6gzt2_U5JZsFlBS7c
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI1Zjg5ZDk3NCIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzNTUsImV4cCI6MTc2MTE1MzE1NSwiaWF0IjoxNzUzMjA0MzU2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.yaBPkqZWJc9lIs1PN17iPKDEFNuvOQaxR3lbCfTt3IA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIyZTA4NTdmOCIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjMiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzOTYsImV4cCI6MTc2MTE1MzE5NiwiaWF0IjoxNzUzMjA0Mzk2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.Wt2pvuUu5HSVdzCrNiwkcIh0rxCUg5BwnTQSh1xDrOI
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI5NmE5MTk1OSIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUyNDUiLCJodHRwczovL2xvY2FsaG9zdDo3MjQ4Il0sIm5iZiI6MTc1MzIwNTk2NCwiZXhwIjoxNzYxMTU0NzY0LCJpYXQiOjE3NTMyMDU5NjUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.MADWxPj2Y7aus62_dejruv20vG6qLsq8P20Nhzdjr2k
###

PUT http://localhost:5245/doctor/reservation/5
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIyYmIyN2Q5MiIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjEiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzMzUsImV4cCI6MTc2MTE1MzEzNSwiaWF0IjoxNzUzMjA0MzM2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.vClLBEnYOL90mOoM-jD21D6EYE6gzt2_U5JZsFlBS7c
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI1Zjg5ZDk3NCIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzNTUsImV4cCI6MTc2MTE1MzE1NSwiaWF0IjoxNzUzMjA0MzU2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.yaBPkqZWJc9lIs1PN17iPKDEFNuvOQaxR3lbCfTt3IA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIyZTA4NTdmOCIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjMiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzOTYsImV4cCI6MTc2MTE1MzE5NiwiaWF0IjoxNzUzMjA0Mzk2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.Wt2pvuUu5HSVdzCrNiwkcIh0rxCUg5BwnTQSh1xDrOI
Content-Type: application/json

{ 
  "patientId" : 3,  
  "newDate" : "2024-06-30T16:30:00"
}

###

DELETE http://localhost:5245/doctor/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIyYmIyN2Q5MiIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjEiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzMzUsImV4cCI6MTc2MTE1MzEzNSwiaWF0IjoxNzUzMjA0MzM2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.vClLBEnYOL90mOoM-jD21D6EYE6gzt2_U5JZsFlBS7c
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI1Zjg5ZDk3NCIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzNTUsImV4cCI6MTc2MTE1MzE1NSwiaWF0IjoxNzUzMjA0MzU2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.yaBPkqZWJc9lIs1PN17iPKDEFNuvOQaxR3lbCfTt3IA
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIyZTA4NTdmOCIsInJvbGUiOiJkb2N0b3IiLCJpZCI6IjMiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MjQ1IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI0OCJdLCJuYmYiOjE3NTMyMDQzOTYsImV4cCI6MTc2MTE1MzE5NiwiaWF0IjoxNzUzMjA0Mzk2LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.Wt2pvuUu5HSVdzCrNiwkcIh0rxCUg5BwnTQSh1xDrOI