GET http://localhost:5245/doctor/1

###

PUT http://localhost:5245/doctor/reservation/1
Content-Type: application/json

{ 
  "patientId" : 2,  
  "newDate" : "2024-06-30T18:30:00"
}

###

DELETE http://localhost:5245/doctor/1/7