POST http://localhost:5245/patient/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI2YTA5ZmJkYSIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAyMjc0LCJleHAiOjE3NjExNTEwNzQsImlhdCI6MTc1MzIwMjI3NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.UlyrB09oCrLE_kfstPBuAfhUlpF8snXNcJkQ_htcuBA
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI3Y2RkOWI5ZCIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAwNjI0LCJleHAiOjE3NjExNDk0MjQsImlhdCI6MTc1MzIwMDYyNCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.0qJOszvuUtU-jXhJ66yXWSXwCSsSI4Qp5jhcIcFH8jQ
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiJlNjg4OTFiNiIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIzIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAzNDM5LCJleHAiOjE3NjExNTIyMzksImlhdCI6MTc1MzIwMzQ0MCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.cXXLwBqyXq9dIbe_BoC1Tyr0atE9Yipx8cdaNEMXGPw
Content-Type: application/json

{
    "doctorId": 1,
    "reservationDate": "2025-12-30T07:00:00"
}

###
GET http://localhost:5245/patient/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI2YTA5ZmJkYSIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAyMjc0LCJleHAiOjE3NjExNTEwNzQsImlhdCI6MTc1MzIwMjI3NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.UlyrB09oCrLE_kfstPBuAfhUlpF8snXNcJkQ_htcuBA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI3Y2RkOWI5ZCIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAwNjI0LCJleHAiOjE3NjExNDk0MjQsImlhdCI6MTc1MzIwMDYyNCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.0qJOszvuUtU-jXhJ66yXWSXwCSsSI4Qp5jhcIcFH8jQ
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiJlNjg4OTFiNiIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIzIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAzNDM5LCJleHAiOjE3NjExNTIyMzksImlhdCI6MTc1MzIwMzQ0MCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.cXXLwBqyXq9dIbe_BoC1Tyr0atE9Yipx8cdaNEMXGPw
###
GET http://localhost:5245/patient/reservation/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiIzZTcwOWU2NiIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUyNDUiLCJodHRwczovL2xvY2FsaG9zdDo3MjQ4Il0sIm5iZiI6MTc1Mjc0NTA1MSwiZXhwIjoxNzYwNjkzODUxLCJpYXQiOjE3NTI3NDUwNTIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.DjJu8mBktuddGYvd7AeqYXslbDFxCIVIRLJJwXxgp78

###
PUT http://localhost:5245/patient/reservation/10
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI2YTA5ZmJkYSIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAyMjc0LCJleHAiOjE3NjExNTEwNzQsImlhdCI6MTc1MzIwMjI3NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.UlyrB09oCrLE_kfstPBuAfhUlpF8snXNcJkQ_htcuBA
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI3Y2RkOWI5ZCIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAwNjI0LCJleHAiOjE3NjExNDk0MjQsImlhdCI6MTc1MzIwMDYyNCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.0qJOszvuUtU-jXhJ66yXWSXwCSsSI4Qp5jhcIcFH8jQ
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiJlNjg4OTFiNiIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIzIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAzNDM5LCJleHAiOjE3NjExNTIyMzksImlhdCI6MTc1MzIwMzQ0MCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.cXXLwBqyXq9dIbe_BoC1Tyr0atE9Yipx8cdaNEMXGPw
Content-Type: application/json

{
    "doctorId": 2,
    "reservationDate" : "2025-10-30T16:30:00"
}

###
DELETE http://localhost:5245/patient/reservation/6
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI2YTA5ZmJkYSIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIxIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAyMjc0LCJleHAiOjE3NjExNTEwNzQsImlhdCI6MTc1MzIwMjI3NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.UlyrB09oCrLE_kfstPBuAfhUlpF8snXNcJkQ_htcuBA
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI3Y2RkOWI5ZCIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIyIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMjAwNjI0LCJleHAiOjE3NjExNDk0MjQsImlhdCI6MTc1MzIwMDYyNCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.0qJOszvuUtU-jXhJ66yXWSXwCSsSI4Qp5jhcIcFH8jQ
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hdGlhIiwic3ViIjoibWF0aWEiLCJqdGkiOiI2YWUyYjNlZCIsInJvbGUiOiJwYXRpZW50IiwiaWQiOiIzIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTI0NSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNDgiXSwibmJmIjoxNzUzMDkzMTA3LCJleHAiOjE3NjEwNDE5MDcsImlhdCI6MTc1MzA5MzEwOCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.PJ_GLjRxw0pMRovEmC9XeR_W8p4YGT-vzubhFpnSLuI